spring:
  profiles:
    active: dev

---
#dev配置
spring:
  application:
    name: leemsc-config-dev
  profiles:
    active: dev



---
#test配置
spring:
  application:
    name: leemsc-config-test
  profiles:
    active: test